services: 
  ollama: 
    image: ollama/ollama:latest 
    runtime: nvidia 
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0:11434 
    volumes: 
      - ollama_models:/root/.ollama 
    ports: 
      - "127.0.0.1:11434:11434" # ollama default port, ip for sec
    restart: unless-stopped 
    healthcheck: 
      test: ["CMD", "ollama", "list"] # run ollama list
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    # wait unltil server is ready
    entrypoint: >
      /bin/sh -c "ollama serve &
      until ollama list > /dev/null 2>&1; do sleep 2; done &&
      ollama list | grep -q 'phi3:mini' || ollama pull phi3:mini &&
      wait"

  sangan: 
    image: sangan:latest 
    network_mode: host 
    env_file: .env 
    restart: unless-stopped
    depends_on: 
      ollama: 
        condition: service_healthy
volumes: 
  ollama_models: {}
