apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: sangan-rolebinding 
  namespace: default 
subjects: 
- kind: ServiceAccount 
  name: sangan-sa 
  namespace: default 
roleRef: 
  kind: Role 
  name: sangan-role 
  apiGroup: rbac.authorization.k8s.io
